name: full_test
on: [push]
jobs: 
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          ./setup.py install --user
      - name: Run test
        run: |
          python ./samples/msiempy_setup.py --host 207.179.200.58:4443 --user NGCP --passwd ${{ secrets.esmpass }}
          pytest
